### ISSUE TITLE
P.c doesn't handle portlets

### ISSUE THREAD

**Issue by uschwarz** [plone/Products.contentmigration#6]
Migrated content loses all locally-assigned portlets. 
Source for 2.1.9 doesn't contain the string `portl` nor `col`, so I assume there's simply no attempt to copy it. Even if the name of the manager needed to be hard-coded, having code for the standard side columns would give a person a good starting point.

**Comment by pbauer** [comment]
plone.app.contenttypes has code that migrates portlets when migrating Archetypes content to Dexterity. You could add that to your migrator. 
See https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/migration/migration.py#L59

    def migrate_portlets(src_obj, dst_obj):
        """Copy portlets for all available portletmanagers from one object
        to another.
        Also takes blocked portlet settings into account, keeps hidden portlets
        hidden and skips broken assignments.
        """

        # also take custom portlet managers into account
        managers = [reg.name for reg in getSiteManager().registeredUtilities()
                    if reg.provided == IPortletManager]
        # faster, but no custom managers
        # managers = [u'plone.leftcolumn', u'plone.rightcolumn']

        # copy information which categories are hidden for which manager
        blacklist_status = IAnnotations(src_obj).get(
            CONTEXT_BLACKLIST_STATUS_KEY, None)
        if blacklist_status is not None:
            IAnnotations(dst_obj)[CONTEXT_BLACKLIST_STATUS_KEY] = \
                deepcopy(blacklist_status)

        # copy all portlet assignments (visibilty is stored as annotation
        # on the assignments and gets copied here too)
        for manager in managers:
            column = getUtility(IPortletManager, manager)
            mappings = getMultiAdapter((src_obj, column),
                                       IPortletAssignmentMapping)
            for key, assignment in mappings.items():
                # skip possibly broken portlets here
                if not hasattr(assignment, '__Broken_state__'):
                    add_portlet(dst_obj, assignment, key, manager)
                else:
                    logger.warn(u'skipping broken portlet assignment {0} '
                                'for manager {1}'.format(key, manager))
